# Use container-based infrastructure
sudo: false

branches:
  only:
    - master
    - stable
    - Week2-Vinay

language: scala

jdk: oraclejdk8

scala:
   - 2.10.4
   - 2.12.4

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

env:
  # This splits the build into two parts
  matrix:
    - TEST_COMMAND="scripted sbt-assembly/*"
    - TEST_COMMAND="scripted merging/* caching/*"

script:
  - cd CSVKafka
  - sbt -Dfile.encoding=UTF8 -J-XX:ReservedCodeCacheSize=256M clean build
  - sbt test

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

# Email specific recipient all the time
notifications:
  email:
    recipients:
      - vinaygor11@gmail.com
      - akshaysjk@gmail.com
      secure: "Some/BASE64/STUFF="
    on_success: always # default: change