# Use container-based infrastructure
sudo: true

language: scala

jdk: oraclejdk8

scala:
   - 2.10.4
   - 2.12.4

env:
  # This splits the build into two parts
  matrix:
    - TEST_COMMAND="scripted sbt-assembly/*"
    - TEST_COMMAND="scripted merging/* caching/*"

script:
  - sbt -Dfile.encoding=UTF8 -J-XX:ReservedCodeCacheSize=256M clean build
  - sbt test
